language: node_js
node_js:
  - 12.x 
services:
  - postgresql
cache:
  directories:
  - node_modules
before_script:
  - npm install
  - psql -c 'DROP DATABASE IF EXISTS mydiarytest;' -U postgres
  - psql -c 'CREATE DATABASE mydiarytest;' -U postgres
script:
  - npm run coverage:coveralls
