language: node_js
node_js:
- stable
services:
  - postgresql
addons:
  postgresql: "12"
cache:
  directories:
  - node_modules
before_script:
- npm run install-packages
- psql -c '\i migrations/migrate.sql \q' -U postgres
- psql -c "CREATE ROLE personalprojects WITH LOGIN PASSWORD 'lovely' CREATEDB SUPERUSER;" -U postgres
script:
- npm run coverage
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"