on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: azure/postgresql@v1
      with:
        connection-string: ${{ secrets.POSTGRESQLCONNSTR_AZURE }}
        server-name: diary-app-demo-postgre.postgres.database.azure.com
        plsql-file: "sql/*.sql"