# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    services:
        postgres:
          image: postgres:10.8
          env:
            POSTGRES_USER: okezie
            POSTGRES_PASSWORD: ${{ secretes.postgres_password }}
            POSTGRES_DB: mydiarydev
          ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run coverage:codacy

  codacy-coverage-reporter:
      runs-on: ubuntu-latest
      name: codacy-coverage-reporter
      steps:
        - uses: actions/checkout@master
        - name: Run codacy-coverage-reporter
          uses: codacy/codacy-coverage-reporter-action@master
          with:
            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
            coverage-reports: coverage/*.lcov.info, *.lcov.dat, *.lcov